name: Build Ionic App and Deploy on FTP

on: [push]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master 
        
      - name: Install Angular
        run: npm install -g @angular/cli@latest

      - name: Install Ionic
        run: npm install -g @ionic/cli
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: ng build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.echowhite.com
          username: up@sha.echowhite.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: www/

      - name: Install ionic cordova
        run: npm install -g cordova 

      - name: Add Angular Cordova builders
        run: ng add @ionic/cordova-builders '--skip-confirmation'

      - name: Generate Apk File
        run: ionic cordova build android --prod --device

      - name: Rename APK
        run: mv platforms/android/app/build/outputs/apk/debug/app-debug.apk platforms/android/app/build/outputs/apk/debug/sha.apk

      - name: 📂 Sync APK via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.echowhite.com
          username: up@sha.echowhite.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: platforms/android/app/build/outputs/apk/debug/
          remote-dir: /
